// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheGalacticTournament.Api.Data;

#nullable disable

namespace TheGalacticTournament.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheGalacticTournament.Api.Entities.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BattleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpeciesAId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesBId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerSpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesAId");

                    b.HasIndex("SpeciesBId");

                    b.HasIndex("WinnerSpeciesId");

                    b.ToTable("Battles", (string)null);
                });

            modelBuilder.Entity("TheGalacticTournament.Api.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PowerLevel")
                        .HasColumnType("int");

                    b.Property<string>("SpecialAbility")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Species", (string)null);
                });

            modelBuilder.Entity("TheGalacticTournament.Api.Entities.Battle", b =>
                {
                    b.HasOne("TheGalacticTournament.Api.Entities.Species", "SpeciesA")
                        .WithMany("BattlesAsSpeciesA")
                        .HasForeignKey("SpeciesAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheGalacticTournament.Api.Entities.Species", "SpeciesB")
                        .WithMany("BattlesAsSpeciesB")
                        .HasForeignKey("SpeciesBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheGalacticTournament.Api.Entities.Species", "WinnerSpecies")
                        .WithMany("BattlesWon")
                        .HasForeignKey("WinnerSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SpeciesA");

                    b.Navigation("SpeciesB");

                    b.Navigation("WinnerSpecies");
                });

            modelBuilder.Entity("TheGalacticTournament.Api.Entities.Species", b =>
                {
                    b.Navigation("BattlesAsSpeciesA");

                    b.Navigation("BattlesAsSpeciesB");

                    b.Navigation("BattlesWon");
                });
#pragma warning restore 612, 618
        }
    }
}
