using Microsoft.EntityFrameworkCore;
using TheGalacticTournament.Api.Data;
using TheGalacticTournament.Api.DTOs;
using TheGalacticTournament.Api.Entities;

namespace TheGalacticTournament.Api.Services
{
    /// <summary>
    /// Service responsible for handling all battle-related business logic.
    /// 
    /// This service manages:
    /// - Listing battle history.
    /// - Starting battles between two selected species.
    /// - Starting random battles.
    /// - Determining battle winners.
    /// - Resetting the ranking by deleting battle history.
    /// </summary>
    public class BattleService : IBattleService
    {
        private readonly AppDbContext _context;

        /// <summary>
        /// Initializes a new instance of the BattleService.
        /// </summary>
        /// <param name="context">
        /// Application database context used to access species and battles.
        /// </param>
        public BattleService(AppDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Gets all registered battles ordered from newest to oldest.
        /// </summary>
        /// <returns>
        /// A list of battle results with participating species, winner and battle date.
        /// </returns>
        public async Task<List<BattleResultDto>> GetAllAsync()
        {
            // AsNoTracking is used because this is a read-only query.
            // It improves performance by avoiding unnecessary change tracking.
            var battles = await _context.Battles
                .AsNoTracking()
                .Include(x => x.SpeciesA)
                .Include(x => x.SpeciesB)
                .Include(x => x.WinnerSpecies)
                .OrderByDescending(x => x.BattleDate)
                .ToListAsync();

            // Converts database entities into DTOs before returning them to the controller.
            return battles.Select(MapToDto).ToList();
        }

        /// <summary>
        /// Starts a battle between two selected species.
        /// </summary>
        /// <param name="request">
        /// DTO containing the IDs of the two species that will battle.
        /// </param>
        /// <returns>
        /// The battle result including the winner and the reason why it won.
        /// </returns>
        /// <exception cref="InvalidOperationException">
        /// Thrown when the same species is selected for both sides of the battle.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when one or both species do not exist.
        /// </exception>
        public async Task<BattleResultDto> StartBattleAsync(StartBattleDto request)
        {
            // A species cannot fight against itself.
            if (request.SpeciesAId == request.SpeciesBId)
                throw new InvalidOperationException("A species cannot battle against itself.");

            // Finds both species in the database.
            var speciesA = await _context.Species.FindAsync(request.SpeciesAId);
            var speciesB = await _context.Species.FindAsync(request.SpeciesBId);

            // If either species does not exist, the battle cannot be created.
            if (speciesA == null || speciesB == null)
                throw new KeyNotFoundException("One or both species were not found.");

            // Applies the tournament rules to determine the winner.
            var winnerInfo = DetermineWinner(speciesA, speciesB);

            // Creates a new battle record to store the result in the database.
            var battle = new Battle
            {
                SpeciesAId = speciesA.Id,
                SpeciesBId = speciesB.Id,
                WinnerSpeciesId = winnerInfo.Winner.Id,
                BattleDate = DateTime.UtcNow
            };

            _context.Battles.Add(battle);
            await _context.SaveChangesAsync();

            // Assigns navigation properties manually so the battle can be mapped to a DTO
            // without querying the database again.
            battle.SpeciesA = speciesA;
            battle.SpeciesB = speciesB;
            battle.WinnerSpecies = winnerInfo.Winner;

            var result = MapToDto(battle);

            // Uses the detailed reason generated by DetermineWinner.
            result.ResultReason = winnerInfo.Reason;

            return result;
        }

        /// <summary>
        /// Starts a random battle between two different registered species.
        /// </summary>
        /// <returns>
        /// The result of the random battle.
        /// </returns>
        /// <exception cref="InvalidOperationException">
        /// Thrown when there are fewer than two species registered.
        /// </exception>
        public async Task<BattleResultDto> StartRandomBattleAsync()
        {
            // Gets all species without tracking because this query is only used
            // to select two random species.
            var species = await _context.Species
                .AsNoTracking()
                .ToListAsync();

            // At least two species are required to create a battle.
            if (species.Count < 2)
                throw new InvalidOperationException("At least two species are required to start a random battle.");

            int firstIndex = Random.Shared.Next(species.Count);
            int secondIndex;

            // Ensures that the second species is different from the first one.
            do
            {
                secondIndex = Random.Shared.Next(species.Count);
            }
            while (secondIndex == firstIndex);

            // Reuses the normal battle logic instead of duplicating the same rules here.
            return await StartBattleAsync(new StartBattleDto
            {
                SpeciesAId = species[firstIndex].Id,
                SpeciesBId = species[secondIndex].Id
            });
        }

        /// <summary>
        /// Determines the winner between two species based on the tournament rules.
        /// </summary>
        /// <param name="speciesA">
        /// First species participating in the battle.
        /// </param>
        /// <param name="speciesB">
        /// Second species participating in the battle.
        /// </param>
        /// <returns>
        /// The winning species and the reason why it won.
        /// </returns>
        private static (Species Winner, string Reason) DetermineWinner(Species speciesA, Species speciesB)
        {
            // Rule 1: The species with the highest power level wins.
            if (speciesA.PowerLevel > speciesB.PowerLevel)
            {
                return (speciesA, $"{speciesA.Name} wins because it has a higher power level.");
            }

            if (speciesB.PowerLevel > speciesA.PowerLevel)
            {
                return (speciesB, $"{speciesB.Name} wins because it has a higher power level.");
            }

            // Rule 2: If both species have the same power level,
            // the species whose name comes first alphabetically wins.
            int comparison = string.Compare(
                speciesA.Name,
                speciesB.Name,
                StringComparison.OrdinalIgnoreCase);

            Species winner = comparison <= 0 ? speciesA : speciesB;

            return (winner, $"{winner.Name} wins because both species have the same power level and its name comes first alphabetically.");
        }

        /// <summary>
        /// Maps a Battle entity to a BattleResultDto.
        /// </summary>
        /// <param name="battle">
        /// Battle entity loaded from the database or created during the current operation.
        /// </param>
        /// <returns>
        /// A DTO containing the battle result information.
        /// </returns>
        private static BattleResultDto MapToDto(Battle battle)
        {
            return new BattleResultDto
            {
                Id = battle.Id,

                SpeciesAId = battle.SpeciesAId,
                SpeciesAName = battle.SpeciesA.Name,
                SpeciesAPowerLevel = battle.SpeciesA.PowerLevel,

                SpeciesBId = battle.SpeciesBId,
                SpeciesBName = battle.SpeciesB.Name,
                SpeciesBPowerLevel = battle.SpeciesB.PowerLevel,

                WinnerSpeciesId = battle.WinnerSpeciesId,
                WinnerName = battle.WinnerSpecies.Name,

                // This generic message is useful when loading battle history.
                // When a battle is started, StartBattleAsync replaces this value
                // with a more specific explanation from DetermineWinner.
                ResultReason = battle.SpeciesA.PowerLevel == battle.SpeciesB.PowerLevel
                    ? "Tie resolved alphabetically."
                    : "Winner selected by higher power level.",

                BattleDate = battle.BattleDate
            };
        }

        /// <summary>
        /// Resets the tournament ranking by deleting all battle records.
        /// </summary>
        /// <returns>
        /// A result indicating how many battle records were deleted and a descriptive message.
        /// </returns>
        public async Task<ResetRankingResultDto> ResetRankingAsync()
        {
            // The ranking is calculated from the Battles table.
            // Therefore, resetting the ranking means deleting all battle history.
            var battles = await _context.Battles.ToListAsync();

            var deletedBattles = battles.Count;

            if (deletedBattles > 0)
            {
                _context.Battles.RemoveRange(battles);
                await _context.SaveChangesAsync();
            }

            return new ResetRankingResultDto
            {
                DeletedBattles = deletedBattles,
                Message = deletedBattles == 0
                    ? "Ranking is already reset. No battles were found."
                    : "Ranking was reset successfully. All battle results were removed."
            };
        }
    }
}